// ============================================================
// Three Golden Demo Scenarios — shared by both apps
// ============================================================

import type { Alert, Case, Campaign, Site, ExternalContextSignal, Entity, AlertDetail } from '../types'

// ---- Sites ----
export const SITES: Site[] = [
  { id: 'site-austin', name: 'Austin HQ', city: 'Austin', state: 'TX', lat: 30.2672, lng: -97.7431, openIncidents: 3, activeAlerts: 7, offlineDevices: 1, riskLevel: 'high', externalSignals: 2 },
  { id: 'site-dallas', name: 'Dallas Office', city: 'Dallas', state: 'TX', lat: 32.7767, lng: -96.7970, openIncidents: 1, activeAlerts: 2, offlineDevices: 0, riskLevel: 'medium', externalSignals: 0 },
  { id: 'site-warehouse', name: 'Cedar Park Warehouse', city: 'Cedar Park', state: 'TX', lat: 30.5052, lng: -97.8203, openIncidents: 0, activeAlerts: 1, offlineDevices: 3, riskLevel: 'low', externalSignals: 1 },
]

// ---- Entities ----
export const ENTITIES: Entity[] = [
  { id: 'ent-marcus', type: 'person', label: 'Marcus Webb', siteId: 'site-austin', riskLevel: 'high', metadata: { role: 'Contractor', badgeId: 'B-4421' } },
  { id: 'ent-badge-b4421', type: 'credential', label: 'Badge B-4421 (Marcus Webb)', siteId: 'site-austin', riskLevel: 'high', metadata: {} },
  { id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door', siteId: 'site-austin', zoneId: 'zone-server', riskLevel: 'high', metadata: {} },
  { id: 'ent-cam-c4', type: 'camera', label: 'Camera C4 — Server Room Corridor', siteId: 'site-austin', zoneId: 'zone-server', riskLevel: 'medium', metadata: {} },
  { id: 'ent-unknown', type: 'person', label: 'Unknown Individual (HXT-7291)', siteId: 'site-austin', riskLevel: 'high', metadata: { vehiclePlate: 'HXT-7291' } },
  { id: 'ent-sarah', type: 'person', label: 'Sarah Chen', siteId: 'site-austin', riskLevel: 'low', metadata: { role: 'Employee', dept: 'Engineering' } },
]

// ---- External Context Signals ----
export const EXTERNAL_SIGNALS: ExternalContextSignal[] = [
  {
    id: 'ext-1',
    subtype: 'civil_unrest',
    title: 'Protest march — Downtown Austin',
    description: 'Large organized protest moving east on 6th Street toward Congress Ave. Estimated 400–600 participants. Police escort in place.',
    severity: 'medium',
    affectedSiteIds: ['site-austin'],
    timeHorizon: 'hours',
    source: 'Emergency Alert Platform',
    timestamp: '2026-06-04T11:00:00Z',
    radiusKm: 0.8,
  },
  {
    id: 'ext-2',
    subtype: 'law_enforcement',
    title: 'BOLO — Suspect vehicle near Warehouse',
    description: 'Law enforcement BOLO issued for dark blue sedan, partial plate 7XF. Last seen I-35 northbound near Cedar Park.',
    severity: 'high',
    affectedSiteIds: ['site-warehouse'],
    timeHorizon: 'immediate',
    source: 'Public Safety Feed',
    timestamp: '2026-06-04T14:22:00Z',
  },
  {
    id: 'ext-3',
    subtype: 'weather',
    title: 'Severe thunderstorm warning — Austin metro',
    description: 'NWS severe thunderstorm warning active until 18:00. Hail up to 1" possible. Flash flood watch in effect.',
    severity: 'medium',
    affectedSiteIds: ['site-austin', 'site-warehouse'],
    timeHorizon: 'hours',
    source: 'Weather & Emergency Alert Service',
    timestamp: '2026-06-04T14:00:00Z',
  },
]

// ---- Alerts (Golden Scenario 1: Unauthorized Server Room Access) ----
export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    type: 'reactive',
    severity: 'critical',
    status: 'ready',
    title: 'Unauthorized server room access attempt',
    location: 'Bldg A · Floor 3 · Server Rm 2B',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T14:38:00Z',
    ageSeconds: 42,
    sources: ['Access Control', 'Camera C4'],
    entityRefs: [
      { id: 'ent-marcus', type: 'person', label: 'Marcus Webb' },
      { id: 'ent-door-srv', type: 'door', label: 'Server Room 2B' },
    ],
    nba: {
      recommendationId: 'nba-001',
      responsePhase: 'contain' as const,
      recommendedAction: 'Restrict badge B-4421 immediately + dispatch guard to Floor 3',
      rationale: 'Badge B-4421 (contractor, no work order on file) probed Server Room 2B twice in 4 minutes — still in the building. Restrict the badge now to prevent a third attempt or lateral movement. Guard intercept confirms location.',
      confidence: 0.91,
      urgency: 'immediate',
      alternatives: ['Lock Server Room 2B door remotely only', 'Intercept at stairwell B exit'],
      requiresApproval: false,
      autoExecuteActions: ['Alert zone owner (IT Security)', 'Notify shift supervisor', 'Lock evidence — Camera C4 30 min window', 'Create incident record in background'],
      gatedActions: ['Restrict badge B-4421 — all zones', 'Lock Server Room 2B door remotely', 'Notify HR / Legal'],
    },
    sop: {
      id: 'sop-04',
      title: 'SOP-04: Unauthorized Access',
      incidentType: 'unauthorized_access',
      version: '2.1',
      effectiveDate: '2026-01-15',
      steps: [
        { step: 1, instruction: 'Verify badge logs — do not confront unilaterally' },
        { step: 2, instruction: 'Contact zone owner within 15 min' },
        { step: 3, instruction: 'Preserve all camera Evidence for the prior 30 min' },
        { step: 4, instruction: 'Escalate if unresolved after 10 min' },
        { step: 5, instruction: 'Create Incident record with supporting Evidence' },
      ],
    },
    explanation: 'Badge B-4421 (Marcus Webb, Contractor) triggered two access denials at Server Room 2B at 14:34 and 14:38. Camera C4 confirms presence. No scheduled visit or authorization on record.',
  },
  {
    id: 'alert-002',
    type: 'deterrent',
    severity: 'critical',
    status: 'ready',
    title: 'Watchlisted person approaching East Entry',
    location: 'Perimeter · East Entry · Austin HQ',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T14:35:00Z',
    ageSeconds: 187,
    sources: ['Face Match', 'Emergency Alert Platform'],
    entityRefs: [{ id: 'ent-unknown', type: 'person', label: 'Person of Interest (watchlist)' }],
    nba: {
      recommendationId: 'nba-002',
      responsePhase: 'contain' as const,
      recommendedAction: 'Increase patrol at East Entry + observe — do not approach',
      rationale: 'Watchlisted individual at perimeter — no access attempted yet. Deterrence window still open. Dispatching visible patrol presence may deter entry attempt. Civil unrest 0.8 km away raises overall site risk. Do not approach unilaterally — confirm match with second camera first.',
      confidence: 0.78,
      urgency: 'immediate',
      alternatives: ['Activate Deterrence Playbook DP-03 (auto-actions)', 'Close East Entry — redirect to Main Lobby only'],
      requiresApproval: false,
      autoExecuteActions: ['Alert site security manager', 'Notify all perimeter guards', 'Log deterrence record + evidence'],
      gatedActions: ['Lock East Entry access point', 'Contact LEA liaison', 'Initiate perimeter sweep'],
    },
    sop: {
      id: 'sop-07',
      title: 'SOP-07: Person of Interest at Perimeter',
      incidentType: 'person_of_interest',
      version: '1.4',
      effectiveDate: '2026-02-01',
      steps: [
        { step: 1, instruction: 'Confirm face match with secondary camera angle' },
        { step: 2, instruction: 'Notify site security manager immediately' },
        { step: 3, instruction: 'Do not approach — observe and document' },
        { step: 4, instruction: 'Activate Deterrence Playbook DP-03 if confirmed' },
        { step: 5, instruction: 'Contact LEA liaison if individual attempts entry' },
      ],
    },
    explanation: 'Face match triggered on East Entry camera (83% confidence) against active watchlist entry. Civil unrest signal active 0.8 km away. Time horizon: immediate.',
  },
  {
    id: 'alert-003',
    type: 'reactive',
    severity: 'high',
    status: 'enriching',
    title: 'After-hours motion — Executive Suite',
    location: 'Floor 4 · Executive Suite · Austin HQ',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T02:14:00Z',
    ageSeconds: 45000,
    sources: ['Motion Sensor', 'Camera A7'],
    entityRefs: [],
  },
  {
    id: 'alert-004',
    type: 'reactive',
    severity: 'high',
    status: 'ready',
    title: 'Tailgating detected — Loading Dock',
    location: 'Loading Dock B · Cedar Park Warehouse',
    siteId: 'site-warehouse',
    siteName: 'Cedar Park Warehouse',
    timestamp: '2026-06-04T13:52:00Z',
    ageSeconds: 2760,
    sources: ['Camera W2', 'Door Sensor'],
    entityRefs: [{ id: 'ent-unknown', type: 'person', label: 'Unknown Individual (HXT-7291)' }],
    nba: {
      recommendationId: 'nba-004',
      responsePhase: 'contain' as const,
      recommendedAction: 'Track individual via cameras — confirm location before locking dock',
      rationale: 'Unknown individual inside warehouse. Do not lock dock until location is confirmed — risk of trapping them deeper inside or triggering escalation. Use Camera W5 to track movement, then dispatch guard for intercept. Vehicle HXT-7291 is linked to campaign activity at Austin HQ — treat as coordinated.',
      confidence: 0.84,
      urgency: 'high',
      alternatives: ['Dispatch guard to last known position (near Dock B)', 'Trigger warehouse sweep via intercom'],
      requiresApproval: false,
      autoExecuteActions: ['Alert all warehouse guards + shift supervisor', 'Track via Camera W5 — update location every 60s', 'Lock evidence — Camera W2 + W5', 'Flag Campaign-001 — multi-site activity'],
      gatedActions: ['Lock Loading Dock B door (confirm location first)', 'Initiate warehouse lockdown', 'Contact law enforcement — BOLO vehicle on site'],
    },
    sop: {
      id: 'sop-02',
      title: 'SOP-02: Tailgating',
      incidentType: 'tailgating',
      version: '1.2',
      effectiveDate: '2026-01-15',
      steps: [
        { step: 1, instruction: 'Verify via camera feed — confirm second individual did not badge in' },
        { step: 2, instruction: 'Track individual movement via camera network' },
        { step: 3, instruction: 'Dispatch nearest guard to area' },
        { step: 4, instruction: 'Do not lock door until individual location is confirmed' },
      ],
    },
    explanation: 'Camera W2 detected two individuals entering Loading Dock B on a single badge swipe. Unknown individual HXT-7291 vehicle plate matches BOLO on file.',
    campaignId: 'campaign-001',
  },
  {
    id: 'alert-005',
    type: 'reactive',
    severity: 'medium',
    status: 'ready',
    title: 'Camera offline — Parking Level 2',
    location: 'Parking Level 2 · Austin HQ',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T12:30:00Z',
    ageSeconds: 7800,
    sources: ['Device Health Monitor'],
    entityRefs: [],
    nba: {
      recommendationId: 'nba-005',
      responsePhase: 'document' as const,
      recommendedAction: 'Dispatch facilities to check camera P2-04',
      rationale: 'Camera P2-04 has been offline for 2h 10m. No weather or power events explain the outage.',
      confidence: 0.72,
      urgency: 'medium',
      alternatives: ['Remote reboot attempt', 'Flag for next maintenance cycle'],
      requiresApproval: false,
      autoExecuteActions: ['Create facilities ticket', 'Flag coverage gap'],
      gatedActions: [],
    },
  },
]

// ---- Alert Details (correlated evidence per alert) ----
export const ALERT_DETAILS: Record<string, AlertDetail> = {
  'alert-001': {
    alertId: 'alert-001',
    person: {
      type: 'known',
      name: 'Marcus Webb',
      role: 'Contractor',
      company: 'SecureBuild LLC',
      badgeId: 'B-4421',
      accessLevel: 'Level 2 (General Areas)',
      department: 'Facilities',
      avatarInitials: 'MW',
      avatarColor: '#DC2626', // red because high risk
    },
    correlatedEvents: [
      {
        id: 'ce-001',
        ts: '14:21',
        type: 'access',
        location: 'Main Lobby — Entry A',
        detail: 'Badge B-4421 granted. Entry logged.',
        granted: true,
      },
      {
        id: 'ce-002',
        ts: '14:24',
        type: 'camera',
        location: 'Lobby Camera L1',
        detail: 'Individual confirmed heading toward elevator bank.',
        cameraPreview: { channel: 'L1', sceneType: 'lobby' },
      },
      {
        id: 'ce-003',
        ts: '14:27',
        type: 'camera',
        location: 'Floor 3 Corridor Camera C4',
        detail: 'Individual arrived Floor 3, Server Room corridor.',
        cameraPreview: { channel: 'C4', sceneType: 'hallway' },
      },
      {
        id: 'ce-004',
        ts: '14:34',
        type: 'access',
        location: 'Server Room 2B Door',
        detail: 'Badge B-4421 DENIED. Insufficient clearance (Level 4+ required).',
        granted: false,
      },
      {
        id: 'ce-005',
        ts: '14:34–14:38',
        type: 'agent',
        location: 'Server Room Corridor',
        detail: 'AI: Individual lingered 4 min 12 sec after denial. Consistent with probing behavior.',
        agentFlag: true,
      },
      {
        id: 'ce-006',
        ts: '14:38',
        type: 'access',
        location: 'Server Room 2B Door',
        detail: 'Badge B-4421 DENIED (2nd attempt). Second denial within 4-minute window.',
        granted: false,
      },
      {
        id: 'ce-007',
        ts: '14:39',
        type: 'camera',
        location: 'Floor 3 Corridor Camera C4',
        detail: 'Individual departing corridor after 2nd denial.',
        cameraPreview: { channel: 'C4', sceneType: 'restricted' },
      },
    ],
    agentSummary: 'Badge B-4421 (Marcus Webb, Contractor) attempted access to Server Room 2B — a Level 4+ restricted zone — twice within 4 minutes. Both denied. Camera C4 confirms 4+ minute loiter. No scheduled work order for Floor 3 on this date. Pattern consistent with access probing.',
  },
  'alert-002': {
    alertId: 'alert-002',
    person: {
      type: 'unknown',
      label: 'Unknown — Watchlist Match',
      watchlistCategory: 'Person of Interest',
      confidence: 83,
      firstSeen: '14:33',
      cameraSightings: ['East Entry Cam E1', 'Perimeter Cam P3'],
      vehiclePlate: null,
      avatarColor: '#D97706',
    },
    correlatedEvents: [
      {
        id: 'ce-a1',
        ts: '14:33',
        type: 'camera',
        location: 'Perimeter Camera P3',
        detail: 'Individual approached East Entry on foot from parking lot.',
        cameraPreview: { channel: 'P3', sceneType: 'exterior' },
      },
      {
        id: 'ce-a2',
        ts: '14:34',
        type: 'agent',
        location: 'East Entry Camera E1',
        detail: 'Face match: Watchlist entry matched at 83% confidence. Active watchlist category: Person of Interest.',
        agentFlag: true,
      },
      {
        id: 'ce-a3',
        ts: '14:35',
        type: 'camera',
        location: 'East Entry Camera E1',
        detail: 'Individual paused at East Entry, did not attempt badge swipe. Appeared to survey entry point.',
        cameraPreview: { channel: 'E1', sceneType: 'lobby' },
      },
      {
        id: 'ce-a4',
        ts: '14:35',
        type: 'agent',
        location: 'External Signal Correlation',
        detail: 'Civil unrest signal active 0.8 km from site. Emergency Alert Platform severity: Medium. Time horizon: hours.',
        agentFlag: true,
      },
    ],
    agentSummary: 'Face match triggered on East Entry Camera E1 (83% confidence) against active watchlist entry. Individual observed surveying entry point without attempting access. Concurrent civil unrest signal active 0.8 km away elevates overall risk. No access attempt made yet — deterrence action recommended before escalation.',
  },
  'alert-004': {
    alertId: 'alert-004',
    person: {
      type: 'unknown',
      label: 'Unknown Individual',
      watchlistCategory: null,
      confidence: null,
      firstSeen: '13:52',
      cameraSightings: ['Loading Dock Cam W2', 'Warehouse Interior Cam W5'],
      vehiclePlate: 'HXT-7291',
      avatarColor: '#9CA3AF',
    },
    correlatedEvents: [
      {
        id: 'ce-b1',
        ts: '13:51',
        type: 'camera',
        location: 'Exterior Parking Cam W1',
        detail: 'Dark sedan (plate HXT-7291) parked near Loading Dock B entrance.',
        cameraPreview: { channel: 'W1', sceneType: 'parking' },
      },
      {
        id: 'ce-b2',
        ts: '13:52',
        type: 'access',
        location: 'Loading Dock B Door',
        detail: 'Badge W-0093 (J. Rivera, Warehouse Staff) granted access. Door held open — tailgate detected.',
        granted: true,
        tailgate: true,
      },
      {
        id: 'ce-b3',
        ts: '13:52',
        type: 'camera',
        location: 'Loading Dock Camera W2',
        detail: 'Second individual followed credentialed employee through door without badging.',
        cameraPreview: { channel: 'W2', sceneType: 'restricted' },
      },
      {
        id: 'ce-b4',
        ts: '13:54',
        type: 'camera',
        location: 'Warehouse Interior Cam W5',
        detail: 'Unregistered individual moving through warehouse interior unescorted.',
        cameraPreview: { channel: 'W5', sceneType: 'hallway' },
      },
      {
        id: 'ce-b5',
        ts: '13:55',
        type: 'agent',
        location: 'Cross-Site Correlation',
        detail: 'AI: Vehicle HXT-7291 linked to Campaign-001. Same vehicle associated with Austin HQ contractor badge probing earlier today.',
        agentFlag: true,
      },
    ],
    agentSummary: 'Vehicle HXT-7291 parked outside Loading Dock B. Unknown individual tailgated through door behind credentialed employee. Camera W5 confirms unescorted movement inside warehouse. Vehicle plate cross-matched to Campaign-001 (multi-site activity — also linked to Austin HQ access probing incident).',
  },
}

// ---- Campaign ----
export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'campaign-001',
    title: 'HXT-7291 Multi-Site Activity',
    hypothesis: 'Vehicle HXT-7291 linked to tailgating at Cedar Park Warehouse and unauthorized access probing at Austin HQ. Same contractor badge patterns observed across both sites within 4-hour window.',
    incidentIds: ['inc-001', 'inc-004'],
    entityRefs: [
      { id: 'ent-unknown', type: 'person', label: 'Unknown Individual (HXT-7291)' },
      { id: 'ent-marcus', type: 'person', label: 'Marcus Webb' },
    ],
    detectedAt: '2026-06-04T14:40:00Z',
    status: 'active',
  },
]

// ---- Case (Golden Scenario 1: Server Room Investigation) ----
export const MOCK_CASES: Case[] = [
  {
    id: 'case-001',
    incidentId: 'inc-001',
    title: 'Unauthorized server room access — Marcus Webb',
    severity: 'critical',
    status: 'investigating',
    owner: 'J. Torres',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    createdAt: '2026-06-04T14:40:00Z',
    updatedAt: '2026-06-04T15:12:00Z',
    sla: { dueAt: '2026-06-05T14:40:00Z', breached: false },
    entityRefs: [
      { id: 'ent-marcus', type: 'person', label: 'Marcus Webb' },
      { id: 'ent-badge-b4421', type: 'credential', label: 'Badge B-4421' },
      { id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door' },
      { id: 'ent-cam-c4', type: 'camera', label: 'Camera C4' },
    ],
    evidenceRefs: ['ev-001', 'ev-002', 'ev-003', 'ev-004'],
    timeline: [
      {
        id: 'tl-001',
        timestamp: '2026-06-04T14:21:00Z',
        type: 'access',
        title: 'Badge swipe — Main Lobby',
        detail: 'Marcus Webb (B-4421) entered Main Lobby. Access granted.',
        entityRefs: [{ id: 'ent-marcus', type: 'person', label: 'Marcus Webb' }],
        evidenceRefs: ['ev-001'],
        isAIGenerated: false,
      },
      {
        id: 'tl-002',
        timestamp: '2026-06-04T14:28:00Z',
        type: 'camera',
        title: 'Camera C4 — approached Server Room corridor',
        detail: 'Individual confirmed by Camera C4 walking toward Server Room 2B corridor.',
        entityRefs: [{ id: 'ent-cam-c4', type: 'camera', label: 'Camera C4' }],
        evidenceRefs: ['ev-002'],
        isAIGenerated: true,
        cameraPreview: { channel: 'C4', sceneType: 'hallway' },
      },
      {
        id: 'tl-003',
        timestamp: '2026-06-04T14:34:00Z',
        type: 'access',
        title: 'Access DENIED — Server Room 2B (attempt 1)',
        detail: 'Badge B-4421 denied. Reason: Insufficient clearance. Zone restricted to Level 4+.',
        entityRefs: [{ id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door' }],
        evidenceRefs: ['ev-003'],
        isAIGenerated: false,
        flagged: true,
      },
      {
        id: 'tl-004',
        timestamp: '2026-06-04T14:36:00Z',
        type: 'agent',
        title: 'AI: 4-min loiter detected',
        detail: 'Agent analysis: individual remained in Server Room corridor for 4 min 12 sec after denial. Consistent with probing behavior.',
        entityRefs: [],
        evidenceRefs: [],
        isAIGenerated: true,
        flagged: true,
      },
      {
        id: 'tl-005',
        timestamp: '2026-06-04T14:38:00Z',
        type: 'access',
        title: 'Access DENIED — Server Room 2B (attempt 2)',
        detail: 'Badge B-4421 denied again. Second attempt within 4-minute window.',
        entityRefs: [{ id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door' }],
        evidenceRefs: ['ev-003'],
        isAIGenerated: false,
        flagged: true,
      },
      {
        id: 'tl-006',
        timestamp: '2026-06-04T14:40:00Z',
        type: 'access',
        title: 'Badge swipe — Stairwell B exit',
        detail: 'Marcus Webb exited via Stairwell B. Building departure unconfirmed.',
        entityRefs: [{ id: 'ent-marcus', type: 'person', label: 'Marcus Webb' }],
        evidenceRefs: [],
        isAIGenerated: false,
      },
      {
        id: 'tl-007',
        timestamp: '2026-06-04T14:39:00Z',
        type: 'camera',
        title: 'Camera C4 — departing Server Room corridor',
        detail: 'Individual captured by Camera C4 leaving the Server Room 2B corridor after the second denial.',
        entityRefs: [{ id: 'ent-cam-c4', type: 'camera', label: 'Camera C4' }],
        evidenceRefs: ['ev-004'],
        isAIGenerated: true,
        cameraPreview: { channel: 'C4', sceneType: 'restricted' },
      },
    ],
    campaignId: 'campaign-001',
    openQuestions: [
      'Was Marcus Webb assigned any work order for Floor 3 on 2026-06-04?',
      'Who issued badge B-4421 and what zones is it authorized for?',
      'Has this badge been used for access probing at other sites?',
    ],
    tags: ['unauthorized-access', 'contractor', 'server-room', 'campaign-001'],
    person: {
      type: 'known' as const,
      name: 'Marcus Webb',
      role: 'Contractor',
      company: 'SecureBuild LLC',
      badgeId: 'B-4421',
      accessLevel: 'Level 2 (General Areas)',
      department: 'Facilities',
      avatarInitials: 'MW',
      avatarColor: '#DC2626',
    },
  },
]
