// ============================================================
// Three Golden Demo Scenarios — shared by both apps
// ============================================================

import type { Alert, Case, Campaign, Site, ExternalContextSignal, Entity } from '../types'

// ---- Sites ----
export const SITES: Site[] = [
  { id: 'site-austin', name: 'Austin HQ', city: 'Austin', state: 'TX', lat: 30.2672, lng: -97.7431, openIncidents: 3, activeAlerts: 7, offlineDevices: 1, riskLevel: 'high', externalSignals: 2 },
  { id: 'site-dallas', name: 'Dallas Office', city: 'Dallas', state: 'TX', lat: 32.7767, lng: -96.7970, openIncidents: 1, activeAlerts: 2, offlineDevices: 0, riskLevel: 'medium', externalSignals: 0 },
  { id: 'site-warehouse', name: 'Cedar Park Warehouse', city: 'Cedar Park', state: 'TX', lat: 30.5052, lng: -97.8203, openIncidents: 0, activeAlerts: 1, offlineDevices: 3, riskLevel: 'low', externalSignals: 1 },
]

// ---- Entities ----
export const ENTITIES: Entity[] = [
  { id: 'ent-marcus', type: 'person', label: 'Marcus Webb', siteId: 'site-austin', riskLevel: 'high', metadata: { role: 'Contractor', badgeId: 'B-4421' } },
  { id: 'ent-badge-b4421', type: 'credential', label: 'Badge B-4421 (Marcus Webb)', siteId: 'site-austin', riskLevel: 'high', metadata: {} },
  { id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door', siteId: 'site-austin', zoneId: 'zone-server', riskLevel: 'high', metadata: {} },
  { id: 'ent-cam-c4', type: 'camera', label: 'Camera C4 — Server Room Corridor', siteId: 'site-austin', zoneId: 'zone-server', riskLevel: 'medium', metadata: {} },
  { id: 'ent-unknown', type: 'person', label: 'Unknown Individual (HXT-7291)', siteId: 'site-austin', riskLevel: 'high', metadata: { vehiclePlate: 'HXT-7291' } },
  { id: 'ent-sarah', type: 'person', label: 'Sarah Chen', siteId: 'site-austin', riskLevel: 'low', metadata: { role: 'Employee', dept: 'Engineering' } },
]

// ---- External Context Signals ----
export const EXTERNAL_SIGNALS: ExternalContextSignal[] = [
  {
    id: 'ext-1',
    subtype: 'civil_unrest',
    title: 'Protest march — Downtown Austin',
    description: 'Large organized protest moving east on 6th Street toward Congress Ave. Estimated 400–600 participants. Police escort in place.',
    severity: 'medium',
    affectedSiteIds: ['site-austin'],
    timeHorizon: 'hours',
    source: 'Emergency Alert Platform',
    timestamp: '2026-06-04T11:00:00Z',
    radiusKm: 0.8,
  },
  {
    id: 'ext-2',
    subtype: 'law_enforcement',
    title: 'BOLO — Suspect vehicle near Warehouse',
    description: 'Law enforcement BOLO issued for dark blue sedan, partial plate 7XF. Last seen I-35 northbound near Cedar Park.',
    severity: 'high',
    affectedSiteIds: ['site-warehouse'],
    timeHorizon: 'immediate',
    source: 'Public Safety Feed',
    timestamp: '2026-06-04T14:22:00Z',
  },
  {
    id: 'ext-3',
    subtype: 'weather',
    title: 'Severe thunderstorm warning — Austin metro',
    description: 'NWS severe thunderstorm warning active until 18:00. Hail up to 1" possible. Flash flood watch in effect.',
    severity: 'medium',
    affectedSiteIds: ['site-austin', 'site-warehouse'],
    timeHorizon: 'hours',
    source: 'Weather & Emergency Alert Service',
    timestamp: '2026-06-04T14:00:00Z',
  },
]

// ---- Alerts (Golden Scenario 1: Unauthorized Server Room Access) ----
export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    type: 'reactive',
    severity: 'critical',
    status: 'ready',
    title: 'Unauthorized server room access attempt',
    location: 'Bldg A · Floor 3 · Server Rm 2B',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T14:38:00Z',
    ageSeconds: 42,
    sources: ['Access Control', 'Camera C4'],
    entityRefs: [
      { id: 'ent-marcus', type: 'person', label: 'Marcus Webb' },
      { id: 'ent-door-srv', type: 'door', label: 'Server Room 2B' },
    ],
    nba: {
      recommendationId: 'nba-001',
      recommendedAction: 'Promote to case + escalate to security lead',
      rationale: 'Badge holder attempted access to restricted zone twice in 4 minutes. No authorization record found. Pattern consistent with probing behavior.',
      confidence: 0.91,
      urgency: 'immediate',
      alternatives: ['Dispatch on-site guard', 'Request supervisor review'],
      requiresApproval: false,
      autoExecuteActions: ['Lock Evidence', 'Notify on-call security'],
      gatedActions: ['Restrict badge access', 'Notify HR/Legal'],
    },
    sop: {
      id: 'sop-04',
      title: 'SOP-04: Unauthorized Access',
      incidentType: 'unauthorized_access',
      version: '2.1',
      effectiveDate: '2026-01-15',
      steps: [
        { step: 1, instruction: 'Verify badge logs — do not confront unilaterally' },
        { step: 2, instruction: 'Contact zone owner within 15 min' },
        { step: 3, instruction: 'Preserve all camera Evidence for the prior 30 min' },
        { step: 4, instruction: 'Escalate if unresolved after 10 min' },
        { step: 5, instruction: 'Create Incident record with supporting Evidence' },
      ],
    },
    explanation: 'Badge B-4421 (Marcus Webb, Contractor) triggered two access denials at Server Room 2B at 14:34 and 14:38. Camera C4 confirms presence. No scheduled visit or authorization on record.',
  },
  {
    id: 'alert-002',
    type: 'deterrent',
    severity: 'critical',
    status: 'ready',
    title: 'Watchlisted person approaching East Entry',
    location: 'Perimeter · East Entry · Austin HQ',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T14:35:00Z',
    ageSeconds: 187,
    sources: ['Face Match', 'Emergency Alert Platform'],
    entityRefs: [{ id: 'ent-unknown', type: 'person', label: 'Person of Interest (watchlist)' }],
    nba: {
      recommendationId: 'nba-002',
      recommendedAction: 'Notify site manager + increase patrol frequency',
      rationale: 'Watchlisted individual matched at East Entry camera with 83% confidence. Concurrent civil unrest signal 0.8 km away elevates risk.',
      confidence: 0.78,
      urgency: 'immediate',
      alternatives: ['Activate deterrence playbook DP-03', 'Contact law enforcement liaison'],
      requiresApproval: false,
      autoExecuteActions: ['Notify site manager', 'Log deterrence event'],
      gatedActions: ['Restrict entry', 'Contact law enforcement'],
    },
    sop: {
      id: 'sop-07',
      title: 'SOP-07: Person of Interest at Perimeter',
      incidentType: 'person_of_interest',
      version: '1.4',
      effectiveDate: '2026-02-01',
      steps: [
        { step: 1, instruction: 'Confirm face match with secondary camera angle' },
        { step: 2, instruction: 'Notify site security manager immediately' },
        { step: 3, instruction: 'Do not approach — observe and document' },
        { step: 4, instruction: 'Activate Deterrence Playbook DP-03 if confirmed' },
        { step: 5, instruction: 'Contact LEA liaison if individual attempts entry' },
      ],
    },
    explanation: 'Face match triggered on East Entry camera (83% confidence) against active watchlist entry. Civil unrest signal active 0.8 km away. Time horizon: immediate.',
  },
  {
    id: 'alert-003',
    type: 'reactive',
    severity: 'high',
    status: 'enriching',
    title: 'After-hours motion — Executive Suite',
    location: 'Floor 4 · Executive Suite · Austin HQ',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T02:14:00Z',
    ageSeconds: 45000,
    sources: ['Motion Sensor', 'Camera A7'],
    entityRefs: [],
  },
  {
    id: 'alert-004',
    type: 'reactive',
    severity: 'high',
    status: 'ready',
    title: 'Tailgating detected — Loading Dock',
    location: 'Loading Dock B · Cedar Park Warehouse',
    siteId: 'site-warehouse',
    siteName: 'Cedar Park Warehouse',
    timestamp: '2026-06-04T13:52:00Z',
    ageSeconds: 2760,
    sources: ['Camera W2', 'Door Sensor'],
    entityRefs: [{ id: 'ent-unknown', type: 'person', label: 'Unknown Individual (HXT-7291)' }],
    nba: {
      recommendationId: 'nba-004',
      recommendedAction: 'Dispatch guard to Loading Dock B + review footage',
      rationale: 'Unregistered individual followed credentialed employee through Loading Dock B without badge swipe.',
      confidence: 0.84,
      urgency: 'high',
      alternatives: ['Lock Loading Dock B remotely', 'Create incident and monitor'],
      requiresApproval: false,
      autoExecuteActions: ['Lock Evidence', 'Notify shift supervisor'],
      gatedActions: ['Lock/restrict dock door'],
    },
    sop: {
      id: 'sop-02',
      title: 'SOP-02: Tailgating',
      incidentType: 'tailgating',
      version: '1.2',
      effectiveDate: '2026-01-15',
      steps: [
        { step: 1, instruction: 'Verify via camera feed — confirm second individual did not badge in' },
        { step: 2, instruction: 'Track individual movement via camera network' },
        { step: 3, instruction: 'Dispatch nearest guard to area' },
        { step: 4, instruction: 'Do not lock door until individual location is confirmed' },
      ],
    },
    explanation: 'Camera W2 detected two individuals entering Loading Dock B on a single badge swipe. Unknown individual HXT-7291 vehicle plate matches BOLO on file.',
    campaignId: 'campaign-001',
  },
  {
    id: 'alert-005',
    type: 'reactive',
    severity: 'medium',
    status: 'ready',
    title: 'Camera offline — Parking Level 2',
    location: 'Parking Level 2 · Austin HQ',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    timestamp: '2026-06-04T12:30:00Z',
    ageSeconds: 7800,
    sources: ['Device Health Monitor'],
    entityRefs: [],
    nba: {
      recommendationId: 'nba-005',
      recommendedAction: 'Dispatch facilities to check camera P2-04',
      rationale: 'Camera P2-04 has been offline for 2h 10m. No weather or power events explain the outage.',
      confidence: 0.72,
      urgency: 'medium',
      alternatives: ['Remote reboot attempt', 'Flag for next maintenance cycle'],
      requiresApproval: false,
      autoExecuteActions: ['Create facilities ticket', 'Flag coverage gap'],
      gatedActions: [],
    },
  },
]

// ---- Campaign ----
export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'campaign-001',
    title: 'HXT-7291 Multi-Site Activity',
    hypothesis: 'Vehicle HXT-7291 linked to tailgating at Cedar Park Warehouse and unauthorized access probing at Austin HQ. Same contractor badge patterns observed across both sites within 4-hour window.',
    incidentIds: ['inc-001', 'inc-004'],
    entityRefs: [
      { id: 'ent-unknown', type: 'person', label: 'Unknown Individual (HXT-7291)' },
      { id: 'ent-marcus', type: 'person', label: 'Marcus Webb' },
    ],
    detectedAt: '2026-06-04T14:40:00Z',
    status: 'active',
  },
]

// ---- Case (Golden Scenario 1: Server Room Investigation) ----
export const MOCK_CASES: Case[] = [
  {
    id: 'case-001',
    incidentId: 'inc-001',
    title: 'Unauthorized server room access — Marcus Webb',
    severity: 'critical',
    status: 'investigating',
    owner: 'J. Torres',
    siteId: 'site-austin',
    siteName: 'Austin HQ',
    createdAt: '2026-06-04T14:40:00Z',
    updatedAt: '2026-06-04T15:12:00Z',
    sla: { dueAt: '2026-06-05T14:40:00Z', breached: false },
    entityRefs: [
      { id: 'ent-marcus', type: 'person', label: 'Marcus Webb' },
      { id: 'ent-badge-b4421', type: 'credential', label: 'Badge B-4421' },
      { id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door' },
      { id: 'ent-cam-c4', type: 'camera', label: 'Camera C4' },
    ],
    evidenceRefs: ['ev-001', 'ev-002', 'ev-003', 'ev-004'],
    timeline: [
      {
        id: 'tl-001',
        timestamp: '2026-06-04T14:21:00Z',
        type: 'access',
        title: 'Badge swipe — Main Lobby',
        detail: 'Marcus Webb (B-4421) entered Main Lobby. Access granted.',
        entityRefs: [{ id: 'ent-marcus', type: 'person', label: 'Marcus Webb' }],
        evidenceRefs: ['ev-001'],
        isAIGenerated: false,
      },
      {
        id: 'tl-002',
        timestamp: '2026-06-04T14:28:00Z',
        type: 'camera',
        title: 'Camera C4 — approached Server Room corridor',
        detail: 'Individual confirmed by Camera C4 walking toward Server Room 2B corridor.',
        entityRefs: [{ id: 'ent-cam-c4', type: 'camera', label: 'Camera C4' }],
        evidenceRefs: ['ev-002'],
        isAIGenerated: true,
      },
      {
        id: 'tl-003',
        timestamp: '2026-06-04T14:34:00Z',
        type: 'access',
        title: 'Access DENIED — Server Room 2B (attempt 1)',
        detail: 'Badge B-4421 denied. Reason: Insufficient clearance. Zone restricted to Level 4+.',
        entityRefs: [{ id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door' }],
        evidenceRefs: ['ev-003'],
        isAIGenerated: false,
        flagged: true,
      },
      {
        id: 'tl-004',
        timestamp: '2026-06-04T14:36:00Z',
        type: 'agent',
        title: 'AI: 4-min loiter detected',
        detail: 'Agent analysis: individual remained in Server Room corridor for 4 min 12 sec after denial. Consistent with probing behavior.',
        entityRefs: [],
        evidenceRefs: [],
        isAIGenerated: true,
        flagged: true,
      },
      {
        id: 'tl-005',
        timestamp: '2026-06-04T14:38:00Z',
        type: 'access',
        title: 'Access DENIED — Server Room 2B (attempt 2)',
        detail: 'Badge B-4421 denied again. Second attempt within 4-minute window.',
        entityRefs: [{ id: 'ent-door-srv', type: 'door', label: 'Server Room 2B Door' }],
        evidenceRefs: ['ev-003'],
        isAIGenerated: false,
        flagged: true,
      },
      {
        id: 'tl-006',
        timestamp: '2026-06-04T14:40:00Z',
        type: 'access',
        title: 'Badge swipe — Stairwell B exit',
        detail: 'Marcus Webb exited via Stairwell B. Building departure unconfirmed.',
        entityRefs: [{ id: 'ent-marcus', type: 'person', label: 'Marcus Webb' }],
        evidenceRefs: [],
        isAIGenerated: false,
      },
    ],
    campaignId: 'campaign-001',
    openQuestions: [
      'Was Marcus Webb assigned any work order for Floor 3 on 2026-06-04?',
      'Who issued badge B-4421 and what zones is it authorized for?',
      'Has this badge been used for access probing at other sites?',
    ],
    tags: ['unauthorized-access', 'contractor', 'server-room', 'campaign-001'],
  },
]
